using System.Text;

namespace Thalamus.Core;

/// <summary>
/// Transpiles a GraphState to a C# class containing executable logic.
/// Uses topological sort (Kahn's algorithm) to determine statement order,
/// then calls provider.GetCodeSnippet() for each node to emit C# code.
/// </summary>
public static class CSharpTranspiler
{
    /// <summary>
    /// Transpiles a graph to a C# string containing a public class ThalamusLogic.
    /// </summary>
    public static string Transpile(GraphState graph, IReadOnlyList<INucleusProvider> providers)
    {
        // Build provider map for O(1) dispatch
        var providerMap = providers.ToDictionary(p => p.ProviderName);

        // Topological sort using Kahn's algorithm
        var executionOrder = TopologicalSort(graph);

        // Assign output variable names: n{index}_{sanitizedPortName}
        var outputVarMap = new Dictionary<(Guid nodeId, string portName), string>();
        int index = 0;
        foreach (var node in executionOrder)
        {
            foreach (var port in node.Schema.Outputs)
            {
                var sanitized = SanitizeName(port.Name);
                outputVarMap[(node.Id, port.Name)] = $"n{index}_{sanitized}";
            }
            index++;
        }

        // Build reverse lookup: (inputNodeId, inputPortName) → (outputNodeId, outputPortName)
        var synapseByInput = graph.Synapses.ToDictionary(
            s => (s.InputNodeId, s.InputPortName),
            s => (s.OutputNodeId, s.OutputPortName));

        // Generate C# code
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by DreamCraft Thalamus");
        sb.AppendLine("// Do not edit by hand — re-export from the visual graph instead.");
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("public class ThalamusLogic");
        sb.AppendLine("{");
        sb.AppendLine("    public void Execute()");
        sb.AppendLine("    {");

        if (executionOrder.Count == 0)
        {
            sb.AppendLine("        // Graph is empty.");
        }
        else
        {
            index = 0;
            foreach (var node in executionOrder)
            {
                // Build inputVars: port name → variable/expression
                var inputVars = new Dictionary<string, string>();
                foreach (var port in node.Schema.Inputs)
                {
                    if (synapseByInput.TryGetValue((node.Id, port.Name), out var source))
                    {
                        if (outputVarMap.TryGetValue(source, out var varName))
                            inputVars[port.Name] = varName;
                    }
                    else
                    {
                        // Unconnected input: use default literal
                        inputVars[port.Name] = GetDefaultLiteral(port);
                    }
                }

                // Build outputVars: port name → variable name
                var outputVars = new Dictionary<string, string>();
                foreach (var port in node.Schema.Outputs)
                    outputVars[port.Name] = outputVarMap[(node.Id, port.Name)];

                // Emit node comment
                sb.AppendLine($"        // [{node.Schema.ProviderName}] {node.Schema.Name}");

                // Get code snippet from provider
                string? snippet = null;
                if (providerMap.TryGetValue(node.Schema.ProviderName ?? "", out var provider))
                    snippet = provider.GetCodeSnippet(node.Schema, inputVars, outputVars);

                if (snippet != null)
                {
                    // Merge inputVars and outputVars for placeholder substitution
                    var allVars = new Dictionary<string, string>(inputVars);
                    foreach (var (k, v) in outputVars)
                        allVars[k] = v;

                    // Replace {portName} placeholders with actual variable names
                    var lines = snippet.Split('\n');
                    foreach (var line in lines)
                    {
                        var trimmed = line.Trim();
                        if (string.IsNullOrWhiteSpace(trimmed)) continue;

                        // Replace placeholders
                        var processed = trimmed;
                        foreach (var (portName, varName) in allVars)
                            processed = processed.Replace("{" + portName + "}", varName);

                        sb.AppendLine("        " + processed);
                    }
                }
                else
                {
                    sb.AppendLine("        // ⚠ No transpiler implementation for this node type");
                }

                sb.AppendLine();
                index++;
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Topological sort using Kahn's algorithm (BFS with in-degree tracking).
    /// Returns nodes in execution order. Cyclic nodes are skipped.
    /// </summary>
    private static List<PlacedNode> TopologicalSort(GraphState graph)
    {
        // Initialize in-degree and successor tracking
        var inDegree = new Dictionary<Guid, int>();
        var successors = new Dictionary<Guid, List<Guid>>();

        foreach (var node in graph.Nodes)
        {
            inDegree[node.Id] = 0;
            successors[node.Id] = [];
        }

        // Build dependency graph
        foreach (var synapse in graph.Synapses)
        {
            inDegree[synapse.InputNodeId]++;
            successors[synapse.OutputNodeId].Add(synapse.InputNodeId);
        }

        // Kahn's BFS: seed with in-degree == 0 nodes
        var queue = new Queue<Guid>();
        foreach (var node in graph.Nodes)
            if (inDegree[node.Id] == 0)
                queue.Enqueue(node.Id);

        var executionOrder = new List<PlacedNode>();
        var nodeMap = graph.Nodes.ToDictionary(n => n.Id);

        while (queue.Count > 0)
        {
            var nodeId = queue.Dequeue();
            executionOrder.Add(nodeMap[nodeId]);

            // Decrement in-degree of successors; enqueue when in-degree hits 0
            foreach (var successorId in successors[nodeId])
            {
                inDegree[successorId]--;
                if (inDegree[successorId] == 0)
                    queue.Enqueue(successorId);
            }
        }

        return executionOrder;
    }

    /// <summary>
    /// Returns the default C# literal for an unconnected input port.
    /// Special case: bool ports named "Enabled" default to true (not false),
    /// to match the semantics of Execute() methods.
    /// </summary>
    private static string GetDefaultLiteral(PortSchema port) => (port.Type, port.Name) switch
    {
        ("bool", "Enabled") => "true",  // Enabled defaults to true in Execute()
        ("int", _)          => "0",
        ("float", _)        => "0f",
        ("bool", _)         => "false",
        ("string", _)       => "\"\"",
        ("uint32", _)       => "1u",    // 0 is invalid for xorshift
        _                   => "null"
    };

    /// <summary>
    /// Sanitizes a port name for use in a C# variable name.
    /// Replaces spaces and hyphens with underscores.
    /// </summary>
    private static string SanitizeName(string name)
        => name.Replace(" ", "_").Replace("-", "_");
}
